# Generated by Django 5.1 on 2024-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('ACCNO', models.CharField(max_length=12)),
                ('CustState', models.CharField(max_length=150)),
                ('custpin', models.CharField(max_length=6)),
                ('DPD', models.CharField(max_length=100)),
            ],
        ),
    ]
